theme: jekyll-theme-minimal
title: Austin Hinkel, Ph.D.
description: Astrophysicist, Data Scientist, and Teacher
logo: /assets/img/hikingPicArch_smaller.jpg
google_analytics: G-DHT8P9N8PG




#author:
#  name             : "Austin Hinkel"
#  bio              : "Astrophysicist, Data Scientist, and Teacher"
#  location         : "Colorado Springs, CO"
#  employer         : "Colorado College"
#  googlescholar    : "https://scholar.google.com/citations?user=Act8eHcAAAAJ&hl=en&oi=ao"
#  orcid            : "https://orcid.org/0000-0002-9785-914X"
#  twitter          : "iHinkthere4iam"








